### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by RafaAlkhamry2020** [slyne-dev/NeuralSim#2]
What are  the requirements that i need to run the project with interface because i tried to run the simulation but its not any interface just code of generation . Generation is go on , So what i need to run the project as you shown in the video where the gene movement through generations.

**Comment by oxi-dev0** [comment]
In the default config (config/config.ini), a render of the simulation will be generated every 100 generations. this will be output to 'out/xxx.mp4'. This is generated with ffmpeg (which is included with the built exe), and can be viewed in VLC. As far as i am aware, the videos dont work in the standard windows media viewer.

**Comment by RafaAlkhamry2020** [comment]
I means the requirements for setup the project in my pc

**Comment by RafaAlkhamry2020** [comment]
![Screenshot 2022-06-10 181447](https://user-images.githubusercontent.com/67509711/173103604-d5ff273b-5b56-4491-8d05-b1870080ed71.png)

**Comment by oxi-dev0** [comment]
If you want to visualise the neural map, look inside the /out/ folder for the neural map exports (.nm files), then, in the command prompt run `NeuralSim.exe -v "out/x-xx-NeuralMap.nm"`,
