### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by RafaAlkhamry2020** [slyne-dev/NeuralSim#4]
I cant understand what is the error the syntax is true
![Screenshot 2022-06-10 184643](https://user-images.githubusercontent.com/67509711/173114563-9d1e169c-86e4-49e7-b5b9-cb8585b4f05f.png)

**Comment by oxi-dev0** [comment]
oh thats the .ini config file reader, please make sure that when you clone this repository, you use the tag "--recursive" so that it pulls all submodules.

**Comment by oxi-dev0** [comment]
(e.g `git clone --recursive "https://github.com/oxi-dev0/NeuralSim`)
